name: Line Message

# Controls when the action will run. 
on:
  issues:
    types: [opened]

jobs:
  line_push_message_job:
    runs-on: ubuntu-latest
    name: LINE push message
    steps:
    - name: Push LINE message
      uses: ufoo68/line-push-message@v1.3
      with:
        user-id: ${{ secrets.USER_ID }}
        message: '新職缺通知【 ${{ github.event.issue.title }} 】 詳細資訊請參考: ${{ github.event.issue.html_url }}'
        channel-access-token: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
