name: Line Message

# Controls when the action will run. 
on:
  issues:
    types: [opened]

jobs:
  line_push_message_job:
    runs-on: ubuntu-latest
    name: LINE push message
    steps:
      - name: Push LINE Notify
        uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            新職缺通知：
            【 ${{ github.event.issue.title }} 】

            詳細資訊請參考: ${{ github.event.issue.html_url }}
